### ISSUE TITLE
Ban user functionality missing

### ISSUE THREAD

**Issue by celestebyte** [supabase-community/gotrue-csharp#100]
# Feature request

The way of ban a user and retrieve the ban_duration is missing from the client.

## Is your feature request related to a problem? Please describe.

There is no way to ban a user using the client.

## Describe the solution you'd like

Add the properties in the classes to support banning users and retrieve the information until when a user is banned.

## Describe alternatives you've considered

I can extend the  class `AdminUserAttributes` and add the property but feels external to the client.

## Additional context
Other clients like JS have this functionality already: https://github.com/supabase/auth-js/blob/master/src/lib/types.ts#L431 or in Python: https://github.com/supabase-community/auth-py/blob/main/supabase_auth/types.py#L229

If any information is missing I am happy to add it, 

Also, when is approved to add this functionality in the client I can submit a PR with the changes 😊

**Comment by acupofjose** [comment]
Thanks for the request! Yes that is functionality we need - please feel free to open a PR if you’d like to work on it
