### ISSUE TITLE
Implement `List` and `Update` User

### ISSUE THREAD

**Issue by TheOnlyBeardedBeast** [supabase-community/gotrue-csharp#13]
Hi, I started to work with GoTrue standalone, and I would like to build an admin panel for it using c# on the backend. 

I went through the api docs and the Go implementation and I found out that this client has some missing functions
- listing users (pagination, sorting, filtering) 
- update user by the admin

Are these functions in progress/planned or are you open for a pull request if I would do it, thanks.

**Comment by acupofjose** [comment]
Hey @TheOnlyBeardedBeast if you’re looking to do a PR, I’ll gladly take it! Otherwise I’ll implement it over the weekend. Thanks for the heads up!

**Comment by TheOnlyBeardedBeast** [comment]
@acupofjose I will try to create a PR, If everything goes right, I should find some time tomorrow. If something goes by, I let you know. Thanks for the fast reply.

**Comment by acupofjose** [comment]
@TheOnlyBeardedBeast available in `gotrue-csharp`@2.2.4 and `supabase-csharp`@0.2.8
