### ISSUE TITLE
StatelessClient SignIn "no Route matched with those values"

### ISSUE THREAD

**Issue by fplaras** [supabase-community/gotrue-csharp#20]
Hi, 

I was attempting to use the stateless client to signin a user but I keep getting the message `"no Route matched with those values"`.
Below is my client options configuration where I added both apikey header and Authorization in case it was an issue with headers. The key I am using is the `anon key` and the Url is the `https://<project-ref>.supabase.co`. I appreciate any help and guidance. 

```
_clientOptions = clientOptions ?? new Gotrue.StatelessClient.StatelessClientOptions
            {
                Url = _config["Supabase:ApiUrl"],
                Headers = new Dictionary<string, string> { 
                    { "apikey", _config["Supabase:SystemApiKey"] },
                    { "Authorization", "Bearer " + _config["Supabase:SystemApiKey"] },
                    { "Content-Type", "application/json" },
                }
            };

var userSession = await Gotrue.StatelessClient.SignIn(signInModel.Email, signInModel.Password, _clientOptions);
```

I was following this example
```
# replace <project-ref> with your own project reference
# and SUPABASE_KEY with your anon api key
curl -X POST 'https://<project-ref>.supabase.co/auth/v1/magiclink' \
-H "apikey: SUPABASE_KEY" \
-H "Content-Type: application/json" \
```

**Comment by fplaras** [comment]
I just realized that the SignIn methods are missing the actual endpoint `/auth` and `version`. Wouldn't the endpoints be defined by the method being called and not established by the applications consuming the library?

**Comment by acupofjose** [comment]
@fplaras hope you had a happy New Year! 

The `gotrue-csharp` library is meant to be server agnostic. From the stateless client, you'll have to use something to the equivalent of what is seen in the `supabase-csharp` repo ([Supabase/Client.cs#L244](https://github.com/supabase-community/supabase-csharp/blob/45f010e80a399310f4c920bda5635a9b80b5369a/Supabase/Client.cs#L244)).

```c#
public string AuthUrlFormat { get; set; } = "{0}/auth/v1";
```

So for your case, just switch out the URL parameter to something more like:

```c#
_clientOptions = clientOptions ?? new Gotrue.StatelessClient.StatelessClientOptions
{
    Url = "https://<project-ref>.supabase.co/auth/v1",
    // ... etc
};
```
