### ISSUE TITLE
Session.CreatedAt is always DateTime.Now

### ISSUE THREAD

**Issue by JohnathanWaring** [supabase-community/gotrue-csharp#26]
Hi,

Apologies if I am overlooking something, but after my session is deserialized, all the values are set correctly except CreatedAt. CreatedAt is always DateTime.Now (due to private set) which results in session.ExpiresAt() returning the incorrect time for that particular session:
https://github.com/supabase-community/gotrue-csharp/blob/master/Gotrue/Session.cs#L27

With the AutoRefreshToken property set to true and starting my app with a saved session I know has expired, the Supabase client will initialise no problem, but any call made will return 403 as the JWT has expired. However, the Session believes it valid.

Is there some other way I need to set session.CreatedAt() when deserializing my session?

Kind Regards,
John Waring

**Comment by JohnathanWaring** [comment]
There appears to be an issue with how DateTime is being serialised in app. I ran the same code as a unit test from the gotrue-csharp repo and CreatedAt is set correctly.

Closing this issue.

**Comment by acupofjose** [comment]
Glad you got it figured out!
