### ISSUE TITLE
VerifyOTP(string phone, string token) does not support email OTP verification 

### ISSUE THREAD

**Issue by bhemala** [supabase-community/gotrue-csharp#41]
# Feature request
VerifyOTP supports only phone OTP verification unline supabase js library. 

## Is your feature request related to a problem? Please describe.
I would like to send OTP by email with:
`Supabase.Client.Instance.Auth.SendMagicLink("my@email.com")`

I set .Token to the Magic link instead of .ConfirmationURL. This way user gets verification token.
`<p>Verification code: <code>{{ .Token }}</code></p>`

I need verify this token by VerifyOTP() the same way as in supabase js library
`await supabase.auth.verifyOTP({
  email,
  token,
  type: 'magiclink'
})`

## Describe the solution you'd like
Implement compatible interface with supabase js library.

**Comment by acupofjose** [comment]
@bhemala thanks for the issue - this is available in v2.4.7!

**Comment by bhemala** [comment]
perfekt! thanks!
