### ISSUE TITLE
Please add: VerifyOTP(string email, string token, EmailOtpType type = EmailOtpType.Signup)

### ISSUE THREAD

**Issue by BasBBakker** [supabase-community/gotrue-csharp#49]
This is a great library! Thanks!

I had one request:
Currently you have implemented
 Task<TSession?> VerifyOTP(string email, string token, EmailOtpType type = EmailOtpType.MagicLink);

Can you also add:
 Task<TSession?> VerifyOTP(string email, string token, EmailOtpType type = EmailOtpType.**Signup**);

It would be great to use OTP to verify an email.

Thanks!

Bas

**Comment by acupofjose** [comment]
Can do!

**Comment by BasBBakker** [comment]
Thank you! I really appreciate the work you have done on this.
There are very few products like Supabase with a good C# library.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by acupofjose** [comment]
@BasBBakker thanks - glad to hear you're finding it useful!

I'm a little confused on your request - the third parameter is just set as a default parameter, the signature already accepts  `EmailOtpType.Signup` as a third parameter?

So:
```c#
await client.VerifyOTP("test@email.com", "123123", EmailOtpType.Signup);
```
is already valid!

**Comment by BasBBakker** [comment]
It does not work.

Logging in through OTP (for a user where email has already been confirmed) works beautifully.

But for  a newly signed up user, it does not work.  It does not return an authenticated user, and in Supabase the “Waiting for verification” does not disappear.

Thanks for your help!
Bas

**Comment by acupofjose** [comment]
Available in 3.1.2 using `SignInWithOtp`!

**Comment by BasBBakker** [comment]
Works beautifully!
Thanks!

**Comment by BasBBakker** [comment]
I try to update the password. I don’t want to use the reset link. If people have forgotten their password they can log in through an OTP.


I update the password through the following code



        var attrs = new UserAttributes
        {
            Email = client.Auth.CurrentUser.Email,
            Password = password,

        };
        var response = await client.Auth.Update(attrs);


When I run this, I get an error message

{"message":"No API key found in request","hint":"No `apikey` request header or url param was found."}


Would you like me to open an issue?

Thanks in advance for fixing it!

Bas
