### ISSUE TITLE
Token refresh every 5s.

### ISSUE THREAD

**Issue by slater1** [supabase-community/gotrue-csharp#73]
What I am seeing is that after the first token refresh (say, after 2880s), subsequent refreshes happen every 5s. This makes my server very busy.

And looking at the `TokenRefresh` class, that is what I would expect it to do:
https://github.com/supabase-community/gotrue-csharp/blob/c34280a1febfed3440c1efa5814b9699d32744e9/Gotrue/TokenRefresh.cs#L149

Have I misunderstood? The same interval should be preserved; maybe I'm using it wrong.

If it should be fixed, I'm happy to submit a PR.

**Comment by wiverson** [comment]
Yup, that’s what it should do - send a pr ftw
