### ISSUE TITLE
RefreshToken-SignIn without AccessToken/Session

### ISSUE THREAD

**Issue by Cegoco11** [supabase-community/gotrue-csharp#92]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, we found some difficulties refreshing tokens in our web app. We use a custom middleware with scoped lifetime to handle multiple users, being the client a non persistent session. So, trying to get a new access token using the refresh cookie is not possible, pointing us to a "Not Logged in." error. (We haven't dive a lot into the code, so maybe there are more conditions and not just this method)

![imagen](https://github.com/supabase-community/gotrue-csharp/assets/32985890/031577b2-6a08-42cc-b47b-4c0ac59f64d0)

## Describe the solution you'd like

We would like to be able to refresh access tokens using the refresh token cookie, without the need of the access token. We think that access tokens are usually short-lived resources and refresh tokens long-lived. That's why we are not understanding the need of the access token since the expiration will not be the same.

## Describe alternatives you've considered

None, as we do not have the session saved.

## Additional context

We noticed that this behavior was previously implemented in the code. We don't know if this was a bug or not, that's why we are creating this as a new feature request.
![imagen](https://github.com/supabase-community/gotrue-csharp/assets/32985890/204ae7b4-11c6-4ce8-a7bb-1b2cc75f61f4)

https://github.com/supabase-community/gotrue-csharp/commit/b097c343b4a0fe756565bf8b59dee3db6ebae804#diff-61e34891b161dc56627598f4dd0d09c704317ca492f3708b5b22627a40633777

Thanks in advance!

**Comment by Cegoco11** [comment]
Thank you for the quick response!

So the workaround could be that we have the `access_token` available, then call the equivalent of `setSession` in the JS Client but in the C# package. (Which I assume it is `GetSessionAsync`)

![imagen](https://github.com/supabase-community/gotrue-csharp/assets/32985890/b1c2fa7b-e105-42f2-a2e7-9849de789b5c)

This way we will be able to call the `RefreshSession` being the `CurrentSession` object populated and being able to go forward in this.
Did I got you right?

**Comment by acupofjose** [comment]
Close! We actually have a `SetSession` [on the client as well](https://supabase-community.github.io/gotrue-csharp/api/Supabase.Gotrue.Client.html?q=setsession#Supabase_Gotrue_Client_SetSession_System_String_System_String_System_Boolean_). But yep, you'll just need to have the `access_token` available!

**Comment by Cegoco11** [comment]
Thank you very much for your help, I'm closing this one!
